# Generated by Django 2.1.3 on 2018-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_content',
            field=models.FileField(null=True, upload_to='content_images'),
        ),
    ]
