# Generated by Django 2.1.3 on 2018-12-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0002_remove_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgs',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imgs/%Y/%m/%d/'),
        ),
    ]
