# Generated by Django 2.1.3 on 2018-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0007_auto_20181209_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
