# Generated by Django 2.1.3 on 2018-12-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0011_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
