# Generated by Django 2.1.3 on 2018-12-10 14:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0014_auto_20181210_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=100),
        ),
    ]
