# Generated by Django 2.1.3 on 2018-12-18 03:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0018_auto_20181210_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='whatsnew',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
