# Generated by Django 2.1.3 on 2018-12-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0019_post_whatsnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='whatsnew',
        ),
    ]
