# Generated by Django 2.1.3 on 2018-12-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0020_remove_post_whatsnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
